apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nfspvc-operator.fullname" . }}-controller-manager
  labels:
  {{- include "nfspvc-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
        {{- include "nfspvc-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: manager
          image: {{ .Values.image.manager.repository }}:{{ .Values.image.manager.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.manager.pullPolicy }}
          command:
          {{- range .Values.manager.command }}
          - {{ . }}
          {{- end }}
          args:
          {{- range .Values.manager.args }}
          - {{ . }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ .Values.config.name }}
          securityContext:
            {{- toYaml .Values.manager.securityContext | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            limits:
              cpu: {{ .Values.manager.resources.limits.cpu }}
              memory: {{ .Values.manager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.manager.resources.requests.cpu }}
              memory: {{ .Values.manager.resources.requests.memory }}
          ports:
            - containerPort: {{ .Values.manager.ports.health.containerPort }}
              name: {{ .Values.manager.ports.health.name }}
              protocol: {{ .Values.manager.ports.health.protocol }}
            - containerPort: {{ .Values.manager.ports.webhook.containerPort }}
              name: {{ .Values.manager.ports.webhook.name }}
              protocol: {{ .Values.manager.ports.webhook.protocol }}
            - containerPort: {{ .Values.manager.ports.https.containerPort }}
              name: {{ .Values.manager.ports.https.name }}
              protocol: {{ .Values.manager.ports.https.protocol }}
          volumeMounts:
          {{- range .Values.manager.volumeMounts }}
          - mountPath: {{ .mountPath }}
            name: {{ .name }}
            readOnly: {{ .readOnly }}
          {{- end }}
      serviceAccountName: {{ include "nfspvc-operator.fullname" . }}-controller-manager
      volumes:
      {{- range .Values.volumes }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secret.secretName }}
          defaultMode: {{ .secret.defaultMode }}
      {{- end }}
